services:
    # Grafana Alloy batches and processes traces sent to it, generating
    # auto-logs from those traces.
    # Includes Metrics, Logs, Traces and Profiles.
    alloy:
        image: grafana/alloy:v1.1.0
        ports:
            - "12347:12345"
            - "12348:12348"
            - "6832:6832"
            - "55679:55679"
        volumes:
            - "./alloy/config.alloy:/etc/alloy/config.alloy"
            - "./alloy/endpoints-cloud.json:/etc/alloy/endpoints.json"
        command: [
            "run",
            "--server.http.listen-addr=0.0.0.0:12345",
            "--stability.level=public-preview",
            "/etc/alloy/config.alloy",
        ]
        # Hashicorp vault
    vault:
        image: hashicorp/vault
        container_name: vault
        hostname: vault
        ports:
            - "8200:8200"
        volumes:
            - ./docker/config.hcl:/vault/config/config.hcl
            - vault-data:/vault/file/
        environment:
            - VAULT_ADDR=http://localhost:8200
        cap_add:
            - IPC_LOCK
        command: server
        networks:
            - self-vault
        restart: always

    vault-init:
        image: hashicorp/vault
        container_name: vault-init
        environment:
            - VAULT_ADDR=http://vault:8200
            - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
        volumes:
            - ./docker/v-root-token:/vault/file/vault-root-token
            - ./docker/vault-init.sh:/usr/local/bin/vault-init.sh
            - vault-data:/vault/file/
        networks:
            - self-vault
        command: /usr/local/bin/vault-init.sh
        restart: on-failure
        depends_on:
            - vault
networks:
    self-vault:
volumes:
    vault-data:
    grafana:
    postgres:

