services:
        # Hashicorp vault
    vault:
        image: hashicorp/vault
        container_name: vault
        hostname: vault
        ports:
            - "8200:8200"
        volumes:
            - ./docker/config.hcl:/vault/config/config.hcl
            - vault-data:/vault/file/
        environment:
            - VAULT_ADDR=http://localhost:8200
        cap_add:
            - IPC_LOCK
        command: server
        networks:
            - self-vault
        restart: always

    vault-init:
        image: hashicorp/vault
        container_name: vault-init
        environment:
            - VAULT_ADDR=http://vault:8200
            - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
        volumes:
            - ./docker/v-root-token:/vault/file/vault-root-token
            - ./docker/vault-init.sh:/usr/local/bin/vault-init.sh
            - vault-data:/vault/file/
        networks:
            - self-vault
        command: /usr/local/bin/vault-init.sh
        restart: on-failure
        depends_on:
            - vault
networks:
    self-vault:
volumes:
    vault-data:

