server:
    port: 2000
spring:
    application:
        name: spring-observe
# Define resource properties for observation
logging:
    pattern:
        console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){yellow} %clr(:){red} %clr(%m){faint}%n"
        file: "{\"timestamp\":\"%d{HH:mm:ss.SSS}\",\"level\":\"%p\",\"traceId\":\"%X{traceId:-}\",\"spanId\":\"%X{spanId:-}\",\"appName\":\"${spring.application.name}\",\"message\":\"%m\"}%n"
    #file:
    #    path: ${HOME}/spring-observe-${server.port}

management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
    metrics:
        distribution:
            percentiles-histogram:
                http:
                    server:
                        requests: true
    observations:
        key-values:
            application: spring-observe
    tracing:
        sampling:
            probability: 1.0
# Define loki url
loki:
    url: <lokiUrl>
    user: <addUserName>
    pass: <addPassword>
    # shttp://localhost:3100/loki/api/v1/push

